openapi: 3.0.0
info:
  title: JANET Simulator REST API
  version: 0.8.0
  contact:
    name: Riccardo Bertini
  description: "REST API for interfacing with the JANET Simulator in the JANET Home Simulation System"
  
servers:
  - url: 'TBD'
    description: "TBD"
    variables: {}
    
paths: 

  # =================================================================================== #
  #                                    LOCATIONS API                                    #
  # =================================================================================== # 
  '/location/{loc_id}':
    summary: JANET Simulator Locations API
    parameters:
      - name: loc_id
        in: path
        required: true
        description: The location ID (unique int > 0)
        schema:
          minimum: 1
          type: 'integer'
          example: 10
    
    
    # ============================== ADD LOCATION ============================== # 
    put:
      summary: "Add a new location"
      description: "Adds a new location and starts its JANET Controller node"
      tags:
        - "Locations API"

      # ------------------- Request Body ------------------- #
      requestBody:
        description: |
          * **name** → The location name (string, optional)
          * **user** → The location user (string, optional)
          * **port** → The location controller's REST port (unique int ≥ 30000)
          * **hostname** → The hostname where to deploy the location controller node (string, required)
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
               - port
               - hostname
              properties:
                name:
                 description: The location Name
                 type: 'string'
                 example: 'office'
                user:
                  description: The location User
                  type: 'string'
                  example: 'janethome@gmail.com'
                port:
                  description: The location controller's REST Port
                  type: 'integer'
                  minimum: 30000
                  example: 30000
                hostname:
                  description: The hostname where to deploy the location controller node
                  type: 'string'
                  example: "www.somePredefinedHost.com"
      
      # --------------------- Responses --------------------- #
      responses:
        '201':
          description: "CREATED (location successfully added)"
          
        '400':
          description: |
           BAD REQUEST
            * Parameter **loc_id** is not an integer
            * Parameter **loc_id** is < 1
            * Parameter **port** is missing
            * Parameter **port** is not an integer
            * Parameter **port** is < 30000
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> Required parameter \"port\" is missing"
        '405':
           $ref: '#/components/responses/GenMethodNotAllowed'
                
        '406':
          description: |
            NOT ACCEPTABLE (The **hostname** does not belong to the list of allowed hosts)
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> The specified \"hostname\" (pippo.com) does not belong to the list of allowed hosts where JANET nodes can be deployed in"         
        '409':
          description: |
            CONFLICT (location **loc_id** already exists)
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> A location with such \"loc_id\" (35) already exists"
                
        '412':
          description: |
            PRECONDITION FAILED (The specified **port** is not available)
            * The **port** is assigned to another location controller
            * The **port** is currently not available in the host OS
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> The specified \"port\" (30000) is already assigned to another location controller"
                
        '415':
          $ref: '#/components/responses/GenUnsupportedMediaType'
          
        '500':
          description: |
           INTERNAL SERVER ERROR
            * The location was added, but an internal error occured in starting its controller node
            * Unknown JSONE parameter mapping
            * Unhandled server error
          content:
            text/plain:
              schema:
                type: string
                example: "<SERVER ERROR> The location was added, but an internal error occured in starting its controller node: {errorReason}"
    
    # ========================== UPDATE LOCATION NAME ========================== # 
    post:
      summary: "Update a location's name"
      description: "Updates the name of an existing location in the JANET Simulator node"
      tags:
        - "Locations API"

      # ------------------- Request Body ------------------- #
      requestBody:
        description: |
          * **name** → The updated location name (string)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                 description: The updated location Name
                 type: 'string'
                 example: 'office'
              
      # --------------------- Responses --------------------- #  
      responses:
        '204':
          description: "NO CONTENT (location name successfully updated)"
          
        '400':
          description: |
           BAD REQUEST
            * Parameter **loc_id** is not an integer
            * Parameter **loc_id** is < 1
            * Parameter **name** is missing
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> Required parameter \"name\" is missing"
                
        '404':
          description: |
           NOT FOUND (location **loc_id** was not found in the JANET Simulator)
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> A location with such \"loc_id\" (9521) does not exist"
                
        '405':
           $ref: '#/components/responses/GenMethodNotAllowed'
        
        '415':
          $ref: '#/components/responses/GenUnsupportedMediaType'
          
        '500':
          $ref: '#/components/responses/GenServerErrorWithBody'
                

    # ============================ DELETE LOCATION ============================ #  
    delete:
      summary: "Delete a location"
      description: "Deletes an existing location from the JANET Home simulation environment, along with all its sublocation and devices"
      tags:
        - "Locations API"
            
      # --------------------- Responses --------------------- #  
      responses:
        '204':
          description: "NO CONTENT (location successfully deleted)"
          
        '400':
          description: |
           BAD REQUEST
            * Parameter **loc_id** is not an integer
            * Parameter **loc_id** is < 1
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> Parameter \"loc_id\" is not an integer (\"ciao\")"
                
        '404':
          description: |
           NOT FOUND (location **loc_id** was not found in the JANET Simulator)
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> A location with such \"loc_id\" (9521) does not exist"
                
        '405':
           $ref: '#/components/responses/GenMethodNotAllowed'
           
        '500':
          description: |
           INTERNAL SERVER ERROR
            * The location along with all its sublocations and devices were deleted from the database, but an internal error occured in stopping their associated nodes
            * Unhandled server error
          content:
            text/plain:
              schema:
                type: string
                example: "<SERVER ERROR> The location along with all its sublocations and devices were deleted from the database, but an internal error occured in stopping their associated nodes: {errorReason}"


  # =================================================================================== #
  #                                  SUBLOCATIONS API                                   #
  # =================================================================================== # 
  '/location/{loc_id}/sublocation/{subloc_id}':
    summary: JANET Simulator Sublocations API
    parameters:
      - name: loc_id
        in: path
        required: true
        description: The location ID (unique int > 0)
        schema:
          minimum: 1
          type: 'integer'
          example: 10
      - name: subloc_id
        in: path
        required: true
        description: The sublocation ID within the location (int > 0, because the name of default sublocations {Loc_id,0} cannot be changed)
        schema:
          minimum: 0
          type: 'integer'
          example: 4
          
   # ======================== UPDATE SUBLOCATION NAME ======================== #
    post:
      summary: "Update a sublocation's name"
      description: "Updates the name of an existing sublocation in the JANET Simulator node"
      tags:
        - "Sublocations API"

      # ------------------- Request Body ------------------- #
      requestBody:
        description: |
          * **name** → The updated sublocation name (string)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                 description: The updated sublocation Name
                 type: 'string'
                 example: 'kitchen'
              
      # --------------------- Responses --------------------- #  
      responses:
        '204':
          description: "NO CONTENT (sublocation name successfully updated)"
          
        '400':
          description: |
           BAD REQUEST
            * Parameter **loc_id** is not an integer
            * Parameter **loc_id** is < 1
            * Parameter **subloc_id** is not an integer
            * Parameter **subloc_id** is < 1
            * Parameter **name** is missing
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> Required parameter \"name\" is missing"
                
        '404':
          description: |
           NOT FOUND (sublocation **{loc_id,subloc_id}** was not found in the JANET Simulator)
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> A sublocation with such \"sub_id\" = {932,74} does not exist"
                
        '405':
           $ref: '#/components/responses/GenMethodNotAllowed'
        
        '415':
          $ref: '#/components/responses/GenUnsupportedMediaType'
          
        '500':
          $ref: '#/components/responses/GenServerErrorWithBody'
  
  
  # =================================================================================== #
  #                                     DEVICES API                                     #
  # =================================================================================== #
  '/device/{dev_id}':
    summary: JANET Simulator Devices API
    parameters:
      - name: dev_id
        in: path
        required: true
        description: The device ID (unique int > 0)
        schema:
          minimum: 1
          type: 'integer'
          example: 5
   
   # =========================== UPDATE DEVICE NAME =========================== #
    post:
      summary: "Update a device's name"
      description: "Updates the name of an existing device in the JANET Simulator node"
      tags:
        - "Devices API"

      # ------------------- Request Body ------------------- #
      requestBody:
        description: |
          * **name** → The updated device name (string)
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                 description: The update device Name
                 type: 'string'
                 example: 'Pinguino Cool&Quiet'
              
      # --------------------- Responses --------------------- #  
      responses:
        '204':
          description: "NO CONTENT (device name successfully updated)"
          
        '400':
          description: |
           BAD REQUEST
            * Parameter **dev_id** is not an integer
            * Parameter **dev_id** is < 1
            * Parameter **name** is missing
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> Required parameter \"name\" is missing"
                
        '404':
          description: |
           NOT FOUND (device **dev_id** was not found in the JANET Simulator)
          content:
            text/plain:
              schema:
                type: string
                example: "<ERROR> A device with such \"dev_id\" (1538) does not exist"
                
        '405':
           $ref: '#/components/responses/GenMethodNotAllowed'
        
        '415':
          $ref: '#/components/responses/GenUnsupportedMediaType'
          
        '500':
          $ref: '#/components/responses/GenServerErrorWithBody'
                
#=============================================================================================# 
                
components:
  
  # =================================================================================== #
  #                           GEN_RESTHANDLER GENERIC RESPONSES                         #
  # =================================================================================== #
  responses:    
  
    # 405 (HTTP Method not allowed in specified path)
    GenMethodNotAllowed:
      description: "METHOD NOT ALLOWED (unsupported HTTP method)"
      content:
        text/plain:
          schema:
            type: string
            example: "<ERROR> Method \"GET\" is not allowed in the specified path"
            
    # 415 (Request body could not be interpreted as JSON)
    GenUnsupportedMediaType:
      description: "UNSUPPORTED MEDIA TYPE (request body could not be interpreted as JSON)"
      content:
        text/plain:
          schema:
            type: string
            example: "<ERROR> Request body could not be interpreted in JSON format"            
    
    # 500 (Generic server error with body parameters)
    GenServerErrorWithBody:
      description: |
        INTERNAL SERVER ERROR
        * Unknown JSONE parameter mapping
        * Unhandled server error
      content:
        text/plain:
          schema:
            type: string
            example: "<UNKNOWN SERVER ERROR> Unknown error: {errorReason}"
            
     # 500 (Generic server error without body parameters)
    GenServerErrorWithoutBody:
      description: |
        INTERNAL SERVER ERROR
        * Unhandled server error
      content:
        text/plain:
          schema:
            type: string
            example: "<UNKNOWN SERVER ERROR> Unknown error: {errorReason}" 